services:
  dfdemo:
    platform: linux/amd64
    image: erdincka/dfdemo:latest
    container_name: dfdemo
    restart: unless-stopped
    environment:
      - clusterName=dfab.io
      - isSecure=true
      - MAPR_TZ=Europe/London
      - TZ=Europe/London
      # CHANGE THIS WITH YOUR DOCKER HOSTNAME/FQDN
      - NIFI_WEB_PROXY_HOST=docker.kayalab.uk:12443
      - NIFI_VERSION=1.28.0
      - NIFI_USER=admin
      # Following password needs to be min 12 chars
      - NIFI_PASSWORD=Admin123.Admin123.
    ports:
      - "8501:8501"  ## required to use app UI
      # - "9443:9443"  ## optional for Installer UI
      - "8443:8443"  ## optional for MCS
      - "2222:22"  ## optional for SSH
      - "12443:12443" ## optional for NiFi
      - "8047:8047" ## optional for Drill
      - "8780:8780" ## optional for Airflow
      - "3000:3000" ## optional for Grafana
    cap_add:
      - SYS_ADMIN
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/entrypoint.sh"]

  db:
    platform: linux/amd64
    image: mysql/mysql-server:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'demodb'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'Admin123.'
      MYSQL_ROOT_PASSWORD: 'Admin123.'
    volumes:
      - mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

  minio:
    platform: linux/amd64
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER='admin'
      - MINIO_ROOT_PASSWORD='Admin123.'
    # ports:
    #   - "9000:9000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - minio-data:/data
    command: server /data

volumes:
  mysql: {}
  minio-data: {}