services:
  dfdemo:
    platform: linux/amd64
    build:
      context: ./mapr
      dockerfile: Dockerfile
      args:
        # - MAPR_REPO=https://package.ezmeral.hpe.com/releases/
        - MAPR_REPO=http://10.1.1.4/mapr # this is my local repo, use the line above for official release
        # Don't change these unless you are using a newer sandbox image
        - NIFI_VERSION=1.28.0
        - MYSQL_CONNECTOR_VERSION=9.3.0
        - UBUNTU_VERSION=22.04
      platforms:
        - "linux/amd64"
    container_name: dfdemo
    restart: unless-stopped
    environment:
      - clusterName=mapr.demo
      - isSecure=true
      - MAPR_TZ=Europe/London
      - TZ=Europe/London
      - NIFI_WEB_PROXY_HOST=docker.kayalab.uk:12443
      - NIFI_VERSION=1.28.0
      - NIFI_USER=admin
      # Following password needs to be min 12 chars
      - NIFI_PASSWORD=Admin123.Admin123.
    ports:
      - "8501:8501"  ## required to use app UI
      - "8443:8443"  ## optional for MCS
      - "2222:22"  ## optional for SSH
      - "12443:12443" ## optional for NiFi
      - "8047:8047" ## optional for Drill
      - "3000:3000" ## optional for Grafana
    cap_add:
      - SYS_ADMIN
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/entrypoint.sh"]

#   mysql:
#     platform: linux/amd64
#     image: mysql/mysql-server:8.0
#     container_name: mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: 'demodb'
#       MYSQL_USER: 'mysql'
#       MYSQL_PASSWORD: 'Admin123.'
#       MYSQL_ROOT_PASSWORD: Admin123.
#     volumes:
#       - mysql:/var/lib/mysql
#       - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

# volumes:
#   mysql: {}
